version: 2

models:
  - name: int_entities_fund
    description: >
      Intermediate model combining fund data from multiple source systems using cross-reference mappings
      to create unified fund entities ready for canonical model consumption.
    columns:
      - name: id
        description: Canonical identifier for the fund (UUID format)
        data_type: string
        tests:
          - not_null
          - unique
      - name: name
        description: Primary fund name (prioritized from admin system)
        data_type: string
        tests:
          - not_null
      - name: type
        description: Type of fund (e.g., Growth Equity, Buyout, Venture Capital)
        data_type: string
      - name: vintage
        description: Fund vintage year
        data_type: int64
      - name: management_fee
        description: Management fee rate as a decimal
        data_type: numeric
      - name: hurdle
        description: Hurdle rate as a decimal
        data_type: numeric
      - name: carried_interest
        description: Carried interest rate as a decimal
        data_type: numeric
      - name: target_commitment
        description: Target fund size in base currency
        data_type: numeric
      - name: incorporated_in
        description: Geographic focus/jurisdiction of the fund
        data_type: string
      - name: base_currency_code
        description: Base currency of the fund (3-character ISO code)
        data_type: string
      - name: created_at
        description: Record creation timestamp
        data_type: string
      - name: updated_at
        description: Record last update timestamp
        data_type: string
      - name: fund_legal_name
        description: Legal name of the fund
        data_type: string
      - name: admin_fund_code
        description: Fund code from the fund administration system
        data_type: string
      - name: crm_fund_id
        description: Fund identifier from the CRM system
        data_type: string
      - name: investment_strategy
        description: Investment strategy of the fund
        data_type: string
      - name: sector_focus
        description: Sector focus of the fund
        data_type: string
      - name: final_size
        description: Final fund size in base currency
        data_type: numeric
      - name: fund_status
        description: Current status of the fund
        data_type: string
      - name: overall_data_quality
        description: Overall data quality rating
        data_type: string
        tests:
          - accepted_values:
              values: ['EXCELLENT', 'GOOD', 'FAIR', 'POOR']
      - name: investment_recommendation
        description: Investment recommendation based on attractiveness score
        data_type: string
        tests:
          - accepted_values:
              values: ['HIGHLY_RECOMMENDED', 'RECOMMENDED', 'CONSIDER', 'NOT_RECOMMENDED']

  - name: int_entities_company
    description: >
      Intermediate model combining company data from multiple source systems using cross-reference mappings
      to create unified company entities with comprehensive entity resolution logic.
    columns:
      - name: id
        description: Canonical identifier for the company (UUID format)
        data_type: string
        tests:
          - not_null
          - unique
      - name: name
        description: Primary company name (prioritized from CRM system)
        data_type: string
        tests:
          - not_null
      - name: website
        description: Company website URL
        data_type: string
      - name: description
        description: Company description
        data_type: string
      - name: currency
        description: Company base currency (3-character ISO code)
        data_type: string
      - name: industry_id
        description: Foreign key to industry table (UUID format)
        data_type: string
      - name: created_at
        description: Record creation timestamp
        data_type: timestamp
      - name: updated_at
        description: Record last update timestamp
        data_type: timestamp
      - name: crm_company_id
        description: Company identifier from the CRM system
        data_type: string
      - name: pm_company_id
        description: Company identifier from the portfolio management system
        data_type: string
      - name: industry_primary
        description: Primary industry classification
        data_type: string
      - name: country_code
        description: ISO country code
        data_type: string
      - name: founded_year
        description: Year the company was founded
        data_type: int64
      - name: employee_count
        description: Number of employees
        data_type: int64
      - name: company_size_category
        description: Company size category based on employee count
        data_type: string
        tests:
          - accepted_values:
              values: ['UNKNOWN', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE']
      - name: investment_status
        description: Current investment status
        data_type: string
        tests:
          - accepted_values:
              values: ['PORTFOLIO_COMPANY', 'FORMER_PORTFOLIO', 'PROSPECT']
      - name: latest_revenue
        description: Latest reported revenue
        data_type: numeric
      - name: latest_ebitda
        description: Latest reported EBITDA
        data_type: numeric
      - name: latest_enterprise_value
        description: Latest enterprise valuation
        data_type: numeric
      - name: overall_data_quality
        description: Overall data quality rating
        data_type: string
        tests:
          - accepted_values:
              values: ['EXCELLENT', 'GOOD', 'FAIR', 'POOR']
      - name: investment_recommendation
        description: Investment recommendation based on attractiveness score
        data_type: string
        tests:
          - accepted_values:
              values: ['HIGHLY_RECOMMENDED', 'RECOMMENDED', 'CONSIDER', 'NOT_RECOMMENDED']

  - name: int_entities_investor
    description: >
      Intermediate model preparing investor master data with enhanced categorization,
      scoring, and comprehensive profiling for fundraising and relationship management.
    columns:
      - name: id
        description: Canonical identifier for the investor (UUID format)
        data_type: string
        tests:
          - not_null
          - unique
      - name: name
        description: Name of the investor
        data_type: string
        tests:
          - not_null
      - name: investor_type_id
        description: Foreign key to investor_type table (UUID format)
        data_type: string
      - name: created_at
        description: Record creation timestamp
        data_type: timestamp
      - name: updated_at
        description: Record last update timestamp
        data_type: timestamp
      - name: investor_code
        description: Primary identifier for the investor from source system
        data_type: string
      - name: standardized_investor_type
        description: Standardized investor type classification
        data_type: string
        tests:
          - accepted_values:
              values: ['PENSION_FUND', 'ENDOWMENT', 'FOUNDATION', 'INSURANCE_COMPANY', 
                      'SOVEREIGN_WEALTH_FUND', 'FAMILY_OFFICE', 'FUND_OF_FUNDS', 
                      'BANK', 'CORPORATE', 'HIGH_NET_WORTH', 'OTHER']
      - name: standardized_country_code
        description: ISO country code of the investor
        data_type: string
      - name: investment_capacity
        description: Investment capacity assessment
        data_type: string
      - name: risk_tolerance
        description: Risk tolerance level
        data_type: string
      - name: compliance_status
        description: Overall compliance status
        data_type: string
        tests:
          - accepted_values:
              values: ['FULLY_COMPLIANT', 'PARTIALLY_COMPLIANT', 'NON_COMPLIANT']
      - name: has_esg_requirements
        description: Whether investor has ESG requirements
        data_type: boolean
      - name: final_investor_classification
        description: Final classification for fundraising purposes
        data_type: string
        tests:
          - accepted_values:
              values: ['TARGET_INVESTOR', 'QUALIFIED_INVESTOR', 'POTENTIAL_INVESTOR', 
                      'PROSPECT_INVESTOR', 'EXCLUDED_INVESTOR']
      - name: engagement_strategy
        description: Recommended engagement strategy
        data_type: string
        tests:
          - accepted_values:
              values: ['DIRECT_SENIOR_ENGAGEMENT', 'STRUCTURED_ENGAGEMENT', 'NURTURE_RELATIONSHIP', 
                      'MONITOR_AND_QUALIFY', 'NO_ENGAGEMENT']

  - name: int_entities_counterparty
    description: >
      Intermediate model consolidating counterparty data from multiple source systems,
      creating unified counterparty entities for service providers, lenders, co-investors, and other external parties.
    columns:
      - name: id
        description: Canonical identifier for the counterparty (UUID format)
        data_type: string
        tests:
          - not_null
          - unique
      - name: name
        description: Name of the counterparty organization
        data_type: string
        tests:
          - not_null
      - name: type
        description: Type of counterparty
        data_type: string
        tests:
          - accepted_values:
              values: ['SERVICE_PROVIDER', 'CO_INVESTOR', 'LENDER', 'VENDOR', 
                      'LEGAL_COUNSEL', 'AUDITOR', 'OTHER']
      - name: country_code
        description: ISO country code (2-character)
        data_type: string
      - name: created_at
        description: Record creation timestamp
        data_type: timestamp
      - name: updated_at
        description: Record last update timestamp
        data_type: timestamp
      - name: primary_contact_name
        description: Name of the primary contact person
        data_type: string
      - name: primary_contact_email
        description: Email of the primary contact person
        data_type: string
      - name: counterparty_category
        description: Category for relationship management
        data_type: string
        tests:
          - accepted_values:
              values: ['PROFESSIONAL_SERVICES', 'ADVISORY_SERVICES', 'FINANCIAL_PARTNERS', 
                      'OPERATIONAL_VENDORS', 'OTHER']
      - name: relationship_status
        description: Current relationship status
        data_type: string
      - name: relationship_strength
        description: Strength of the relationship
        data_type: string
      - name: last_interaction_date
        description: Date of last interaction
        data_type: date
      - name: relationship_priority
        description: Priority level for relationship management
        data_type: string
        tests:
          - accepted_values:
              values: ['HIGH_PRIORITY', 'MEDIUM_PRIORITY', 'LOW_PRIORITY', 'MONITOR_ONLY']
      - name: engagement_strategy
        description: Recommended engagement strategy
        data_type: string
        tests:
          - accepted_values:
              values: ['IMMEDIATE_OUTREACH', 'REGULAR_ENGAGEMENT', 'MAINTAIN_CONTACT', 
                      'PERIODIC_OUTREACH', 'MONITOR_ACTIVITY', 'NO_ACTION_REQUIRED']
      - name: data_quality_rating
        description: Overall data quality rating
        data_type: string
        tests:
          - accepted_values:
              values: ['HIGH', 'MEDIUM', 'LOW']