version: 2

models:
  - name: stg_fund
    description: "Staging table for fund data"
    columns:
      - name: fund_id
        description: "Unique identifier for the fund"
        tests: [not_null]
      - name: fund_code
        description: "Fund code"
        tests: [not_null, unique]
      - name: fund_name
        description: "Name of the fund"
      - name: base_currency_code
        description: "Base currency for the fund"

  - name: stg_investor
    description: "Staging table for investor data"
    columns:
      - name: investor_id
        description: "Unique identifier for the investor"
        tests: [not_null]
      - name: investor_code
        description: "Investor code"
        tests: [not_null, unique]
      - name: investor_name
        description: "Name of the investor"

  - name: stg_company
    description: "Staging table for company data"
    columns:
      - name: company_id
        description: "Unique identifier for the company"
        tests: [not_null]
      - name: company_name
        description: "Name of the company"
        tests: [not_null, unique]
      - name: country_code
        description: "Country code"
      - name: currency_code
        description: "Currency code"

  - name: stg_transactions
    description: "Staging table for transaction data"
    columns:
      - name: natural_key
        description: "Natural key for the transaction"
        tests: [not_null]
      - name: date
        description: "Transaction date"
        tests: [not_null]
      - name: transaction_type
        description: "Type of transaction"
        tests:
          - accepted_values:
              arguments:
                values: ["DRAWDOWN","DISTRIBUTION","DIVIDEND","EXPENSE","MANAGEMENT_FEE"]
      - name: amount
        description: "Transaction amount"
      - name: fund_code
        description: "Fund code"
      - name: investor_code
        description: "Investor code"
